# Generated by Django 4.2.5 on 2023-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="type",
            field=models.CharField(
                choices=[
                    ("dj", "DJ"),
                    ("band", "Band"),
                    ("act", "Live act"),
                    ("venue", "Venue"),
                    ("festival", "Festival"),
                    ("event", "Event organizer"),
                ],
                max_length=200,
            ),
        ),
    ]
