# Generated by Django 4.2.5 on 2023-09-30 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beatmatcher", "0004_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("picture", models.FileField(null=True, upload_to="djs")),
                ("in_house", models.BooleanField()),
                ("booking_url", models.CharField(max_length=200)),
                ("soundcloud_url", models.CharField(max_length=200)),
                ("rate", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
