# Generated by Django 4.2.5 on 2023-09-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0005_dj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dj",
            name="in_house",
        ),
        migrations.AlterField(
            model_name="dj",
            name="booking_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
