# Generated by Django 4.2.5 on 2023-09-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0006_remove_dj_in_house_alter_dj_booking_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dj",
            name="picture",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
