# Generated by Django 4.2.5 on 2023-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0008_bookingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
    ]
