# Generated by Django 4.2.5 on 2023-09-30 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beatmatcher", "0009_bookingrequest_rate_bookingrequest_state"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookingRequest",
            new_name="Booking",
        ),
    ]
