# Generated by Django 4.2.5 on 2023-09-30 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0011_booking_code_booking_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="state",
            new_name="status",
        ),
    ]
