# Generated by Django 4.2.5 on 2023-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0013_rename_arrival_time_booking_set_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="contact_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
