# Generated by Django 4.2.5 on 2023-09-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beatmatcher", "0014_booking_contact_name_booking_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="language",
            field=models.CharField(default="en", max_length=2),
            preserve_default=False,
        ),
    ]
