# Generated by Django 4.2.5 on 2023-10-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="String",
            fields=[
                ("english", models.TextField(primary_key=True, serialize=False)),
                ("translation", models.TextField()),
                ("in_use", models.BooleanField()),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.language")),
            ],
        ),
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.language"),
        ),
    ]
