# Generated by Django 4.2.5 on 2023-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_language_string_alter_settings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="string",
            name="id",
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name="ID"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="string",
            name="english",
            field=models.TextField(),
        ),
    ]
